TWOCHECKOUT_TEST_MERCHANT_ID = 'YOUR-MERCHANT-ID-HERE'
TWOCHECKOUT_TEST_BUYLINK_SECRET_WORD = 'YOUR-MERCHANT-BUY-LINK-SECRET-WORD-HERE'
TWOCHECKOUT_TEST_MERCHANT_SECRET_KEY = 'YOUR-MERCHANT-SECRET-KEY-HERE'
