import twocheckout

# fill you VENDOR_ID & SECRET_KEY from 2Checkout account page
auth_params = {
    'merchant_code': '',
    'secret_key': ''
}

payload = {
    'GIFT_ORDER': '0',
    'SALEDATE': '2021-04-08 16:29:38',
    'PAYMENTDATE': '2021-04-08 16:29:42',
    'REFNO': '148998082',
    'REFNOEXT': 'REST_API_AVANGTE',
    'SHOPPER_REFERENCE_NUMBER': '',
    'ORDERNO': '8978',
    'ORDERSTATUS': 'COMPLETE',
    'PAYMETHOD': 'Visa/MasterCard',
    'PAYMETHOD_CODE': 'CCVISAMC',
    'FIRSTNAME': 'Customer',
    'LASTNAME': '2Checkout',
    'COMPANY': '',
    'REGISTRATIONNUMBER': '',
    'FISCALCODE': '',
    'TAX_OFFICE': '',
    'CBANKNAME': '',
    'CBANKACCOUNT': '',
    'ADDRESS1': 'Test Address',
    'ADDRESS2': '',
    'CITY': 'LA',
    'STATE': 'California',
    'ZIPCODE': '12345',
    'COUNTRY': 'United States of America',
    'COUNTRY_CODE': 'us',
    'PHONE': '',
    'FAX': '',
    'CUSTOMEREMAIL': 'testcustomer@2Checkout.com',
    'FIRSTNAME_D': 'Customer',
    'LASTNAME_D': '2Checkout',
    'COMPANY_D': '',
    'ADDRESS1_D': 'Test Address',
    'ADDRESS2_D': '',
    'CITY_D': 'LA',
    'STATE_D': 'California',
    'ZIPCODE_D': '12345',
    'COUNTRY_D': 'United States of America',
    'COUNTRY_D_CODE': 'us',
    'PHONE_D': '',
    'EMAIL_D': 'testcustomer@2Checkout.com',
    'IPADDRESS': '91.220.121.21',
    'IPCOUNTRY': 'Romania',
    'COMPLETE_DATE': '2021-04-08 16:29:48',
    'TIMEZONE_OFFSET': 'GMT+03:00',
    'CURRENCY': 'USD',
    'LANGUAGE': 'en',
    'ORDERFLOW': 'REGULAR',
    'IPN_PID[]': '35144095',
    'IPN_PNAME[]': 'Dynamic product',
    'IPN_PCODE[]': '',
    'IPN_EXTERNAL_REFERENCE[]': '',
    'IPN_INFO[]': '',
    'IPN_QTY[]': '1',
    'IPN_PRICE[]': '107.00',
    'IPN_VAT[]': '0.00',
    'IPN_VAT_RATE[]': '0.00',
    'IPN_VER[]': '1',
    'IPN_DISCOUNT[]': '0.00',
    'IPN_PROMOTION_CATEGORY[]': '',
    'IPN_PROMONAME[]': '',
    'IPN_PROMOCODE[]': '',
    'IPN_ORDER_COSTS[]': '0',
    'IPN_SKU[]': '',
    'IPN_PARTNER_CODE': '',
    'IPN_PGROUP[]': '0',
    'IPN_PGROUP_NAME[]': '',
    'MESSAGE_ID': '250833683479',
    'MESSAGE_TYPE': 'COMPLETE',
    'IPN_LICENSE_PROD[]': '35144095',
    'IPN_LICENSE_TYPE[]': 'REGULAR',
    'IPN_LICENSE_REF[]': '9WITYHQ6NF',
    'IPN_LICENSE_EXP[]': '2021-04-10 16:29:42',
    'IPN_LICENSE_START[]': '2021-04-08 16:29:42',
    'IPN_LICENSE_LIFETIME[]': 'NO',
    'IPN_LICENSE_ADDITIONAL_INFO[]': '',
    'IPN_DELIVEREDCODES[]': '',
    'IPN_DOWNLOAD_LINK': '',
    'IPN_TOTAL[]': '107.00',
    'IPN_TOTALGENERAL': '107.00',
    'IPN_SHIPPING': '0.00',
    'IPN_SHIPPING_TAX': '0.00',
    'AVANGATE_CUSTOMER_REFERENCE': '884855078',
    'EXTERNAL_CUSTOMER_REFERENCE': '',
    'IPN_PARTNER_MARGIN_PERCENT': '0.00',
    'IPN_PARTNER_MARGIN': '0.00',
    'IPN_EXTRA_MARGIN': '0.00',
    'IPN_EXTRA_DISCOUNT': '0.00',
    'IPN_COUPON_DISCOUNT': '0.00',
    'IPN_LINK_SOURCE': 'testAPI.com',
    'IPN_COMMISSION': '4.1015',
    'REFUND_TYPE': '',
    'IPN_PRODUCT_OPTIONS_35144095_TEXT[]': 'Name LR',
    'IPN_PRODUCT_OPTIONS_35144095_VALUE[]': 'f21a6009c31851ab5166190e353012bd',
    'IPN_PRODUCT_OPTIONS_35144095_OPTIONAL_VALUE[]': 'f21a6009c31851ab5166190e353012bd',
    'IPN_PRODUCT_OPTIONS_35144095_PRICE[]': '7.00',
    'IPN_PRODUCT_OPTIONS_35144095_OPERATOR[]': 'ADD',
    'IPN_PRODUCT_OPTIONS_35144095_USAGE[]': 'PREPAID',
    'CHARGEBACK_RESOLUTION': 'NONE',
    'CHARGEBACK_REASON_CODE': '',
    'TEST_ORDER': '1',
    'IPN_ORDER_ORIGIN': 'API',
    'FRAUD_STATUS': 'APPROVED',
    'CARD_TYPE': 'visa',
    'CARD_LAST_DIGITS': '1111',
    'CARD_EXPIRATION_DATE': '12/22',
    'GATEWAY_RESPONSE': 'Approved',
    'IPN_DATE': '20210408185911',
    'FX_RATE': '1',
    'FX_MARKUP': '0',
    'PAYABLE_AMOUNT': '102.90',
    'PAYOUT_CURRENCY': 'USD',
    'VENDOR_CODE': '250111206876',
    'PROPOSAL_ID': '',
    'HASH': '8d05499f0933c2e07c8599ff3a2e5338'
}

# instantiate the object ( for auth)
ipn = twocheckout.ipn_helper.IpnHelper(auth_params['secret_key'])
ipn_valid = ipn.is_valid(payload)
ipn_response = ipn.calculate_ipn_response(payload)
print('ipn is valid: ', ipn_valid)
print('ipn response: ', ipn_response)
